### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by SleepingTownCI**
Translations update from [Weblate](http://weblate.sleeping.town) for [Emi's Mods/EMI](http://weblate.sleeping.town/projects/emis-mods/emi/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by exaskye** [comment]
There was an alert on the component, so I thought it might be broken, but apparently it still works fine. Who knows.

You can leave this PR open until more meaningful changes accumulate; it'll keep pushing to its fork.

**Comment by Aegide** [comment]
@SleepingTownCI cool system

**Comment by Roby1164** [comment]
Italian translation.
Compiled and finished, no errors, those indicated, it is not clear why they are marked as an error, but they are correct.

But trying to add it, I find myself with a part of translated items, some not translated, and it seems that other items to translate are missing besides the descriptions, which remain in English !!!
I am attaching a screenshot as an example.
Screenshot_2

**Comment by xllifi** [comment]
Please remove russian, it's probably not updated by anyone except me and I prefer github pull requests
Or it doesn't matter?

**Pull request closed without merging**
